#if !canImport(ObjectiveC)
import XCTest

extension XoodyakTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__XoodyakTests = [
        ("testAEAD", testAEAD),
        ("testHash", testHash),
        ("testMore", testMore),
    ]
}

public func __allTests() -> [XCTestCaseEntry] {
    return [
        testCase(XoodyakTests.__allTests__XoodyakTests),
    ]
}
#endif
