#if !canImport(ObjectiveC)
import XCTest

extension XoodooTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__XoodooTests = [
        ("testXoodoo", testXoodoo),
    ]
}

public func __allTests() -> [XCTestCaseEntry] {
    return [
        testCase(XoodooTests.__allTests__XoodooTests),
    ]
}
#endif
